### ISSUE TITLE
ts-graphql-plugin v4

### ISSUE THREAD

**Issue by Quramy** [Quramy/ts-graphql-plugin#1267]
## Todos

- [x] Breaking changes:
  - [x] Change plugin option's default values
  - [x] Set lower Node.js version to support
- [x] Update example sources 
- [ ] Refinement docs
  - [x] Update VSC gif

## Change plugin option's default values:

| Name                        | v3 Default value | v4 Default value                                                    |
| :-------------------------- | :--------------- | :------------------------------------------------------------------ |
| `tag`                       | `""`             | `{ name: ["gql", "graphql"], ignoreFunctionCallExpression: false }` |
| `enabledGlobalFragments`    | `false`          | `true`                                                              |
| `removeDuplicatedFragments` | `true`           | `true` (Remove from docs)                                           |
